### ISSUE TITLE
An Istallation Problem for WINDOWS OS

### ISSUE THREAD

**Issue by lhinen** [publicsamples/Quetzalcoatl#16]
Hello!

I created a Samples folder in C:\ProgramData\modularsamples\Quetzalcoatl\ and selected it from the plugin, but it looks like this.

Am I doing something wrong?
![スクリーンショット (44)](https://github.com/user-attachments/assets/f43626a5-ae4a-444e-9f8e-e92b9d2ad50c)

Inside C:\ProgramData\modularsamples\Quetzalcoatl\ is the following state.
![スクリーンショット (45)](https://github.com/user-attachments/assets/a6c25d3b-4023-4f5b-ac8b-1721c481bca1)

The Sample folder is currently empty.

**Comment by potroub** [comment]
and it ask for a file wich is not included in the release 
The initial asked file is .hr1 format but no clue wich file it is and i see in all download content not files with that extension

![Screenshot 2024-07-20 154416](https://github.com/user-attachments/assets/7639ed9d-ab8b-4dec-8e15-8987f65bf906)


So need help or where to find this file..also a quick video tutorial for PC to help would be awsome
for not can't use it at all

PeaceR looks cool....but ... no idea about it for now

**Comment by RickTaylor79** [comment]
Have a look at this discussion here:

https://github.com/publicsamples/Quetzalcoatl/discussions/15

If your sample folder is empty make sure you've extracted the [content zips ](https://github.com/publicsamples/Quetzalcoatl/releases/tag/0.6.1)(use 7zip on windows to extract these).

**Comment by lhinen** [comment]
I have checked the discussion in #15, but as other questioners have said, I can't find the .hr1 extension file anywhere.

The contents zip file could not be unzipped with 7zip because of the 001,002 numbers at the end of the file, or perhaps because of an error.

I tried removing the trailing number from the file name, but it is in the same state.

**Comment by RickTaylor79** [comment]
I'm not sure why, 7zip should work with .001, .002 etc files. Anyway, I've uploaded the content as a single zip here:

https://github.com/publicsamples/Quetzalcoatl/releases/download/0.6.2/Quetzalcoatl-Content.zip

I'll be releasing an update in the next couple of days that will make installation much easier. Keep an eye out for that if you're still having problems.

**Comment by RickTaylor79** [comment]
v0.6.5 is now available, hopefully this will resolve some of the issues people have been having getting it up and running:

https://github.com/publicsamples/Quetzalcoatl/releases/tag/0.6.5.1

Closing this issue for now, but feel free to reopen if there are further problems.
