### ISSUE TITLE
Icons for sample loading and other options appear misleading as if everything is to save

### ISSUE THREAD

**Issue by CSumm** [publicsamples/Quetzalcoatl#27]
Not sure if this is temporary, but the UI has disk thumbnails which make me assume it will save my present or changes when the functionality is different. I also expected the labels to be clickable as well, but they aren't.

Here is a screenshot of what I am seeing. I am running Ableton 12, v 0.7.1.
![Screenshot 2024-09-11 175428](https://github.com/user-attachments/assets/dea31fdb-1c22-42b0-92d2-ee993619cd51)

**Comment by RickTaylor79** [comment]
This is fixed in [v0.8.2](https://github.com/publicsamples/Quetzalcoatl/releases/tag/0.8.2)
