### ISSUE TITLE
VST3 not appearing in DAW, and AU will not open.(macOS Catalina) 

### ISSUE THREAD

**Issue by zwerden** [publicsamples/Quetzalcoatl#8]
After unzipping and installation, VST3 is located in finder and in the appropriate extension directory for my DAW(Ableton). however the VST3 does not appear in my DAWs VST3 folder. and The AudioUnit appears but when I try to load it my DAW says it cannot be opened. I am running macOS Catalina.

**Comment by RickTaylor79** [comment]
Hi,

That's odd. I've tested in Live/Ventura and both plugins are detected and loading fine. I don't have Catalina installed, but it _should_ be fine.

Which version of Ableton? Could you please test with another DAW? ([Reaper](https://www.reaper.fm/download.php) is a good choice 'cos it supports both format), this will help up rule out an OS issue. Also it would help to know the exact error message Live gives you when it can't be opened.

Thanks for the report
Rick

**Comment by zwerden** [comment]
Thank You! and we will go with it! I am using a mid 2012 Macbook Pro, so I
will explore work arounds since my mac is intel-based.

an Idea : wrapping it as an Au3 and putting it on the appStore , for Ipad
accessibility.

cheers!

ZW

**Comment by RickTaylor79** [comment]
Hi There! 

I've just uploaded a version that _should_ work in Catalina (tested in Mojave). The VST should also be available now too. 

It's a good idea, it would probably have to be a complete rebuild though. There are GPL libraries in use and these aren't compatible with the App Store policies. Definitely something I'd consider if the Mac/PC version is a success though.

Best
Rick

**Comment by zwerden** [comment]
Hi thank You, the VST and AU have shown up but there is no audio output...
I see midi sending into the plugin, and it is using CPU, but there audio
output after the Quetzalcoatl plugin. nor is there audio from its track or
the master channel. I've inserted other instruments alongside it(which had
outputted expected audio) to further isolate the issue being Quetzal*.

I appreciate the work You've done, I'm not bothered as my macbook is
technically outdated although for dev purposes I am open to help
troubleshoot to get it to work properly.

cheers!
ZW

**Comment by RickTaylor79** [comment]
Sounds like you might not have installed the sample content? See here for details:

https://modularsamples.gumroad.com/p/quetzalcoatl-v0-5-installing-samples

I've tested on an 2012 iMac (i5, quad core) and it's seems to run pretty well (hitting about 12% cpu usage in Live with all voices active).

**Comment by zwerden** [comment]
Yes! That was it! After unzipping and locating the sample folder(within
Quetzalcoatl), the plugin works as expected🎉👍 thank You for Your help
troubleshooting this.

Cheers
-ZW

**Comment by RickTaylor79** [comment]
Great! thanks for the report. Hopefully it performs decently on your Macbook (guessing it should be usable). 

I'm gonna close this issue for now, but if anything else crops up let me know.

**Comment by zwerden** [comment]
Will do, thanks!
